### ISSUE TITLE
Unable to download Skyrim.ini

### ISSUE THREAD

**Issue by AndreiAvinov** [Kvitekvist/FUS#44] opened 2023-03-21 21:08 UTC
> 00:03:24.356 [INFO] (Wabbajack.Installer.StandardInstaller) Found 2705 total files, 474 matching filesize
00:03:24.429 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 1 archives
00:03:24.429 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:03:24.636 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:03:24.636 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
00:03:24.636 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 1 archives
00:03:24.636 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:03:24.636 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Skyrim.ini
00:03:24.647 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Skyrim.ini|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 140
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 397
00:03:24.647 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:03:24.647 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:03:24.647 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:03:24.672 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:03:24.672 [INFO] (Wabbajack.Installer.StandardInstaller) Found 2705 total files, 474 matching filesize
00:03:24.735 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Skyrim.ini (GameFileSourceDownloader+State|SkyrimVR|1.4.15.0|skyrim.ini)
00:03:24.735 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by MariusKlug** [comment] 2023-03-22 08:51
Duplicate of https://github.com/Kvitekvist/FUS/issues/42

**Closed by MariusKlug** 2023-03-22 08:51 UTC
